version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - ENV=PRODUCTION
    depends_on:
      - redis
    command: ["node", "index.js"]

  frontend:
    build:
      context: ./view
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "3000:3000"
    command: ["npm", "start"]

 

networks:
  default:
    driver: bridge
